/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CreditCardResume {
        /**
          * Card amount
         */
        "amount": number;
        /**
          * Card last movement
         */
        "lastmovement": string;
        /**
          * Card limit
         */
        "limit": number;
        /**
          * Card number
         */
        "number": string;
        /**
          * Card type
         */
        "type": number;
    }
}
declare global {
    interface HTMLCreditCardResumeElement extends Components.CreditCardResume, HTMLStencilElement {
    }
    var HTMLCreditCardResumeElement: {
        prototype: HTMLCreditCardResumeElement;
        new (): HTMLCreditCardResumeElement;
    };
    interface HTMLElementTagNameMap {
        "credit-card-resume": HTMLCreditCardResumeElement;
    }
}
declare namespace LocalJSX {
    interface CreditCardResume {
        /**
          * Card amount
         */
        "amount"?: number;
        /**
          * Card last movement
         */
        "lastmovement"?: string;
        /**
          * Card limit
         */
        "limit"?: number;
        /**
          * Card number
         */
        "number"?: string;
        /**
          * Card type
         */
        "type"?: number;
    }
    interface IntrinsicElements {
        "credit-card-resume": CreditCardResume;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "credit-card-resume": LocalJSX.CreditCardResume & JSXBase.HTMLAttributes<HTMLCreditCardResumeElement>;
        }
    }
}
